/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedTicketsNewRouteImport } from './routes/_authenticated/tickets/new'
import { Route as AuthenticatedTicketsTicketIdIndexRouteImport } from './routes/_authenticated/tickets/$ticketId/index'
import { Route as AuthenticatedTicketsTicketIdEditRouteImport } from './routes/_authenticated/tickets/$ticketId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsNewRoute = AuthenticatedTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsTicketIdIndexRoute =
  AuthenticatedTicketsTicketIdIndexRouteImport.update({
    id: '/tickets/$ticketId/',
    path: '/tickets/$ticketId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsTicketIdEditRoute =
  AuthenticatedTicketsTicketIdEditRouteImport.update({
    id: '/tickets/$ticketId/edit',
    path: '/tickets/$ticketId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/tickets/$ticketId/': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/_authenticated/tickets/$ticketId/': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tickets/new'
    | '/tickets/'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tickets/new'
    | '/tickets'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/tickets/new'
    | '/_authenticated/tickets/'
    | '/_authenticated/tickets/$ticketId/edit'
    | '/_authenticated/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/new': {
      id: '/_authenticated/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AuthenticatedTicketsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId/': {
      id: '/_authenticated/tickets/$ticketId/'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId/'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId/edit': {
      id: '/_authenticated/tickets/$ticketId/edit'
      path: '/tickets/$ticketId/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedTicketsNewRoute: typeof AuthenticatedTicketsNewRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedTicketsTicketIdEditRoute: typeof AuthenticatedTicketsTicketIdEditRoute
  AuthenticatedTicketsTicketIdIndexRoute: typeof AuthenticatedTicketsTicketIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTicketsNewRoute: AuthenticatedTicketsNewRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedTicketsTicketIdEditRoute: AuthenticatedTicketsTicketIdEditRoute,
  AuthenticatedTicketsTicketIdIndexRoute:
    AuthenticatedTicketsTicketIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
